/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-07 23:24:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class oferecerCarona_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/NavBarLogado.jsp", Long.valueOf(1570490607516L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"pt-br\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("    <link rel='stylesheet' type='text/css' media='screen' href='Css/oferecerCarona.css'>\n");
      out.write("    <link rel=\"shortcut icon\" href=\"img/softcar-blue-icon.png\" type=\"image/x-png\">\n");
      out.write("    <title>SoftCar - Oferecer Carona</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- ----------- NavBar ------------- -->\n");
      out.write("     ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("       \n");
      out.write("        <style>\n");
      out.write("            *{\n");
      out.write("                margin: 0;\n");
      out.write("                padding: 0;\n");
      out.write("            }\n");
      out.write("            /* icons */\n");
      out.write("            i{\n");
      out.write("                padding-right: 8px;\n");
      out.write("            }\n");
      out.write("            /* Css da nav bar */\n");
      out.write("            .cabeça{\n");
      out.write("                width: 100%;\n");
      out.write("                height: 10.5%;\n");
      out.write("                background: rgb(255, 255, 255);\n");
      out.write("                font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;\n");
      out.write("                font-size: 18px;\n");
      out.write("                box-shadow: 0px 0px 7px rgb(216, 215, 215);\n");
      out.write("                position: fixed;\n");
      out.write("                z-index: 2;\n");
      out.write("            }\n");
      out.write("            .divLogo{\n");
      out.write("                float: left;\n");
      out.write("                margin-left: 15px;  \n");
      out.write("                margin-top: -20px;  \n");
      out.write("            }\n");
      out.write("            .logo{\n");
      out.write("                width: 180px;\n");
      out.write("                height: 12vh;\n");
      out.write("                background-size: cover;\n");
      out.write("                margin-top: 16px;\n");
      out.write("            }\n");
      out.write("            .first-nav{\n");
      out.write("                list-style: none;\n");
      out.write("                position: relative;\n");
      out.write("                float: right;\n");
      out.write("                z-index: 1;\n");
      out.write("            }\n");
      out.write("            .first-nav ul{\n");
      out.write("                list-style-type: none;\n");
      out.write("                position: relative;\n");
      out.write("                margin-top: -3px;\n");
      out.write("            }\n");
      out.write("            .first-nav ul li {\n");
      out.write("                list-style: none;\n");
      out.write("                position: relative;\n");
      out.write("                width: 280px;\n");
      out.write("                float: right;\n");
      out.write("                text-align: right;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .first-nav ul ul{\n");
      out.write("                position: absolute;\n");
      out.write("                visibility: hidden;\n");
      out.write("            }\n");
      out.write("            .first-nav ul ul li{\n");
      out.write("                border-bottom: solid 1px rgb(202, 202, 202);\n");
      out.write("                float:none; \n");
      out.write("            }\n");
      out.write("            .aNav{\n");
      out.write("                border: none;\n");
      out.write("                text-decoration: none;\n");
      out.write("                color: #069;\n");
      out.write("                text-align: center;\n");
      out.write("            }\n");
      out.write("            #aNavUm{\n");
      out.write("                padding-right: 20px;\n");
      out.write("            }\n");
      out.write("            .AMaior{\n");
      out.write("                padding-left: 35px;\n");
      out.write("                padding-bottom: 10px;\n");
      out.write("                display: block;\n");
      out.write("            }\n");
      out.write("            .nameUser{\n");
      out.write("                display: inline-block;\n");
      out.write("                vertical-align: middle;\n");
      out.write("                margin: 0;\n");
      out.write("                color:#069;\n");
      out.write("                font-weight: normal;\n");
      out.write("                line-height: normal;\n");
      out.write("                font-size: 16px;\n");
      out.write("                padding-left:20px;\n");
      out.write("                margin-top: -75px;\n");
      out.write("            }\n");
      out.write("            .aMenu{\n");
      out.write("                padding: 12px;\n");
      out.write("                display: block;\n");
      out.write("                text-decoration: none;\n");
      out.write("                text-align: left;\n");
      out.write("                color: #069;\n");
      out.write("                font-size: 15px;\n");
      out.write("            }\n");
      out.write("            .first-nav ul li:hover ul{\n");
      out.write("                transition: all .4s;\n");
      out.write("                visibility: visible;\n");
      out.write("            }\n");
      out.write("            .first-nav ul ul li a{\n");
      out.write("                border-left: solid 1px rgb(202, 202, 202);\n");
      out.write("                background-color:#f9f9f9;\n");
      out.write("            }\n");
      out.write("            .first-nav ul ul li a:hover{\n");
      out.write("                background-color: #f1f0f0;\n");
      out.write("            }\n");
      out.write("            .first-nav ul li ul{\n");
      out.write("                margin-top: 18.4px;\n");
      out.write("            }\n");
      out.write("            .liNav{\n");
      out.write("                margin-top:30px;\n");
      out.write("                padding-bottom: 20px;\n");
      out.write("            }\n");
      out.write("            .ImgPerfil {\n");
      out.write("                width: 50px;\n");
      out.write("                height: 50px;\n");
      out.write("                display: inline-block;\n");
      out.write("                vertical-align: middle;\n");
      out.write("                border-radius:50%;\n");
      out.write("                background-size: cover;\n");
      out.write("                margin-left: -30px;\n");
      out.write("                margin-top: 20px;\n");
      out.write("                float: left;\n");
      out.write("            }\n");
      out.write("            label[for=\"bt-menu\"]{\n");
      out.write("                padding-right: 15px;\n");
      out.write("                font-family: Arial;\n");
      out.write("                text-align: right;\n");
      out.write("                font-size: 24px;\n");
      out.write("                cursor: pointer;\n");
      out.write("                height: 50px;\n");
      out.write("                display: none;\n");
      out.write("            }\n");
      out.write("            #bt-menu{\n");
      out.write("                display: none;\n");
      out.write("            }\n");
      out.write("            @media(max-width: 1200px){\n");
      out.write("                label[for=\"bt-menu\"]{\n");
      out.write("                    display: block;\n");
      out.write("                    margin-top: 15px;\n");
      out.write("                }\n");
      out.write("                #bt-menu:checked ~ .first-nav{\n");
      out.write("                    margin-right: 0; \n");
      out.write("                }\n");
      out.write("                .first-nav{\n");
      out.write("                    margin-right: -100%;\n");
      out.write("                    transition: all .4s;\n");
      out.write("                    padding-top: 0px;\n");
      out.write("                    margin-top: 3px;\n");
      out.write("                }\n");
      out.write("                .first-nav ul li{\n");
      out.write("                    text-align: center;\n");
      out.write("                    float: none;\n");
      out.write("                    background: white;\n");
      out.write("                }\n");
      out.write("                #aNavUm{\n");
      out.write("                    padding-right: 0px;\n");
      out.write("                }\n");
      out.write("                .aNav{\n");
      out.write("                    color:coral;\n");
      out.write("                    font-weight: normal;\n");
      out.write("                    line-height: normal;\n");
      out.write("                    padding: 0px;\n");
      out.write("                }\n");
      out.write("                .first-nav ul ul li a{\n");
      out.write("                    background-color: #f9f9f9;\n");
      out.write("                    border: solid 1px rgb(217, 237, 247);\n");
      out.write("                    color: #069;\n");
      out.write("                }\n");
      out.write("                .first-nav ul ul{\n");
      out.write("                    padding: 0px;\n");
      out.write("                    position: static;\n");
      out.write("                    overflow: hidden;\n");
      out.write("                    max-height: 0;\n");
      out.write("                    transition: all .4s;\n");
      out.write("                    width: 100%;\n");
      out.write("                }\n");
      out.write("                .first-nav ul li:hover ul{\n");
      out.write("                    visibility: visible;\n");
      out.write("                    height: auto;\n");
      out.write("                    max-height: 500px;\n");
      out.write("                }\n");
      out.write("                .liNav{\n");
      out.write("                    padding-top: 10px;\n");
      out.write("                    padding-bottom: 10px;\n");
      out.write("                    margin-top: 0px;\n");
      out.write("                    border-top: solid 1px rgb(217, 237, 247);\n");
      out.write("                }\n");
      out.write("                .divlogo{\n");
      out.write("                    margin-left: 30%;\n");
      out.write("                 }\n");
      out.write("            }\n");
      out.write("            @media(max-width: 511px){\n");
      out.write("                label[for=\"bt-menu\"]{\n");
      out.write("                    display: block;\n");
      out.write("                    margin-top: 15px;\n");
      out.write("                }\n");
      out.write("                #bt-menu:checked ~ .first-nav{\n");
      out.write("                    margin-right: 0; \n");
      out.write("                }\n");
      out.write("                .first-nav{\n");
      out.write("                    margin-right: -100%;\n");
      out.write("                    transition: all .4s;\n");
      out.write("                    padding-top: 0px;\n");
      out.write("                    margin-top: -33px;\n");
      out.write("                }\n");
      out.write("                .first-nav ul li{\n");
      out.write("                    text-align: center;\n");
      out.write("                    float: none;\n");
      out.write("                    background: white;\n");
      out.write("                }\n");
      out.write("                #aNavUm{\n");
      out.write("                    padding-right: 0px;\n");
      out.write("                }\n");
      out.write("                .aNav{\n");
      out.write("                    color:coral;\n");
      out.write("                    font-weight: normal;\n");
      out.write("                    line-height: normal;\n");
      out.write("                    padding: 0px;\n");
      out.write("                }\n");
      out.write("                .first-nav ul ul li a{\n");
      out.write("                    background-color: #f9f9f9;\n");
      out.write("                    border: solid 1px rgb(217, 237, 247);\n");
      out.write("                    color: #069;\n");
      out.write("                }\n");
      out.write("                .first-nav ul ul{\n");
      out.write("                    padding: 0px;\n");
      out.write("                    position: static;\n");
      out.write("                    overflow: hidden;\n");
      out.write("                    max-height: 0;\n");
      out.write("                    transition: all .4s;\n");
      out.write("                    width: 100%;\n");
      out.write("                }\n");
      out.write("                .first-nav ul li:hover ul{\n");
      out.write("                    visibility: visible;\n");
      out.write("                    height: auto;\n");
      out.write("                    max-height: 500px;\n");
      out.write("                }\n");
      out.write("                .liNav{\n");
      out.write("                    padding-top: 10px;\n");
      out.write("                    padding-bottom: 10px;\n");
      out.write("                    margin-top: 0px;\n");
      out.write("                    border-top: solid 1px rgb(217, 237, 247);\n");
      out.write("                }\n");
      out.write("                .divlogo{\n");
      out.write("                    margin-left: 30%;\n");
      out.write("                 }\n");
      out.write("            }\n");
      out.write("            /* --------------- Perfil -----------------*/\n");
      out.write("            .s {\n");
      out.write("                background-color: #4CAF50;\n");
      out.write("                color: white;\n");
      out.write("                padding: 14px 20px;\n");
      out.write("                margin: 10px 10px 0px 0px;\n");
      out.write("                border: none;\n");
      out.write("                cursor: pointer;\n");
      out.write("                width: 10%;\n");
      out.write("                font-size:20px;\n");
      out.write("            }\n");
      out.write("            .btns{\n");
      out.write("                margin: 0px 0px 0px 60%; \n");
      out.write("                margin-top: -20px; \n");
      out.write("            }\n");
      out.write("            .btnEditImg{\n");
      out.write("                margin: 0px 0px 0px 25%; \n");
      out.write("                margin-top: -20px; \n");
      out.write("\n");
      out.write("            }\n");
      out.write("            .dadosUser, .dadosProf, .dadosTempo, .dadosCont{\n");
      out.write("                margin-top: 10px;\n");
      out.write("            }\n");
      out.write("            .textosMain{\n");
      out.write("\n");
      out.write("                font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;\n");
      out.write("                font-size: 25px;\n");
      out.write("                color: coral;\n");
      out.write("            }\n");
      out.write("            .textosSeg{\n");
      out.write("\n");
      out.write("                font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;\n");
      out.write("                font-size: 20px;\n");
      out.write("                color: #069;\n");
      out.write("                margin-top: 10px;\n");
      out.write("            }\n");
      out.write("            .imgcontainer {\n");
      out.write("                text-align: center;\n");
      out.write("                margin: 24px 0 12px 0;\n");
      out.write("                position: relative;\n");
      out.write("            }\n");
      out.write("            #trocaFoto{\n");
      out.write("                display: none;\n");
      out.write("            }\n");
      out.write("            #fotoUser[for=\"trocaFoto\"]{\n");
      out.write("                display: block;\n");
      out.write("            }\n");
      out.write("            .avatar {\n");
      out.write("                background-size: cover;\n");
      out.write("                margin-top: -70px;\n");
      out.write("                margin-left: 42%;\n");
      out.write("                width: 100px;\n");
      out.write("                height:100px;\n");
      out.write("                border-radius: 50%;\n");
      out.write("            }\n");
      out.write("            .modal {\n");
      out.write("                margin-top: 70px;\n");
      out.write("                text-align: center;\n");
      out.write("                display:none;\n");
      out.write("                position: fixed;\n");
      out.write("                z-index: 1;\n");
      out.write("                left: 0;\n");
      out.write("                top: 0;\n");
      out.write("                width: 100%;\n");
      out.write("                min-width: 200px;\n");
      out.write("                overflow: auto;\n");
      out.write("                background-color: rgba(0,0,0,0.4);\n");
      out.write("            }\n");
      out.write("            .modal-content {\n");
      out.write("                background-color: #fefefe;\n");
      out.write("                margin: 4% auto 15% auto;\n");
      out.write("                border: 1px solid #888;\n");
      out.write("                width: 40%; \n");
      out.write("                min-width: 200px;\n");
      out.write("                padding-bottom: 30px;\n");
      out.write("            }\n");
      out.write("            .close {\n");
      out.write("                position: absolute;\n");
      out.write("                right: 8px;\n");
      out.write("                margin-top: 40px;\n");
      out.write("                color: #000;\n");
      out.write("                font-size: 35px;\n");
      out.write("                font-weight: bold;\n");
      out.write("            }\n");
      out.write("            .close:hover,.close:focus {\n");
      out.write("                color: red;\n");
      out.write("                cursor: pointer;\n");
      out.write("            }\n");
      out.write("            .animate {\n");
      out.write("                animation: zoom 0.6s\n");
      out.write("            }\n");
      out.write("            @keyframes zoom {\n");
      out.write("                from {transform: scale(0)} \n");
      out.write("                to {transform: scale(1)}\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            @media(max-width: 1200px){\n");
      out.write("                .avatar{\n");
      out.write("                    margin-left: 40%;\n");
      out.write("                }\n");
      out.write("                .btns{\n");
      out.write("                    margin: 0px 0px 0px 60%; \n");
      out.write("                    margin-top: -20px; \n");
      out.write("                }\n");
      out.write("                .btnEditImg{\n");
      out.write("                    margin: 0px 0px 0px 30%; \n");
      out.write("                    margin-top: -20px; \n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            @media(max-width: 820px){\n");
      out.write("                .avatar{\n");
      out.write("                    margin-left: 35%;\n");
      out.write("                }\n");
      out.write("                .btns{\n");
      out.write("                    margin: 0px 0px 0px 0%; \n");
      out.write("                    margin-top: 10px; \n");
      out.write("                }\n");
      out.write("                .btnEditImg{\n");
      out.write("                    margin: 0px 0px 0px 40%; \n");
      out.write("                    margin-top: -20px; \n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            @media(max-width: 730px){\n");
      out.write("                .avatar{\n");
      out.write("                    margin-left: 30%;\n");
      out.write("                }\n");
      out.write("                .btns{\n");
      out.write("                    margin: 0px 0px 0px 0%; \n");
      out.write("                    margin-top: 10px; \n");
      out.write("                }\n");
      out.write("                .btnEditImg{\n");
      out.write("                    margin: 0px 0px 0px 40%; \n");
      out.write("                    margin-top: -20px; \n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            @media(max-width: 600px){\n");
      out.write("                .avatar{\n");
      out.write("                    margin-left: 25%;\n");
      out.write("                }\n");
      out.write("                .btns{\n");
      out.write("                    margin: 0px 0px 0px 0%; \n");
      out.write("                    margin-top: 10px; \n");
      out.write("                }\n");
      out.write("                .btnEditImg{\n");
      out.write("                    margin: 0px 0px 0px 40%; \n");
      out.write("                    margin-top: -20px; \n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("\n");
      out.write("            @media(max-width: 485px){\n");
      out.write("                .avatar{\n");
      out.write("                    margin-left: 20%;\n");
      out.write("                }\n");
      out.write("                .btns{\n");
      out.write("                    margin: 0px 0px 0px 0%; \n");
      out.write("                    margin-top: 10px; \n");
      out.write("                }\n");
      out.write("                .btnEditImg{\n");
      out.write("                    margin: 0px 0px 0px 50%; \n");
      out.write("                    margin-top: -20px; \n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("     <!-- --------------- NavBarLOgado ---------- -->\n");
      out.write("    <header class=\"cabeça\" id=\"cabeça\">\n");
      out.write("        <div class=\"divLogo\" ><a href=\"homeDepoisDeLogar.jsp\"><img class=\"logo\" src=\"img/softcar-blue.png\" alt=\"\"></a></div>\n");
      out.write("            <input type=\"checkbox\" id=\"bt-menu\">\n");
      out.write("            <label for=\"bt-menu\">&#9776;</label>\n");
      out.write("            \n");
      out.write("            <nav class=\"first-nav\">\n");
      out.write("                <ul>\n");
      out.write("                    <li class=\"liNav\"><a class=\"aNav\" id=\"aNavUm\" >Nome do User<i class=\"fas fa-angle-double-down\" style=\"padding-left: 8px;\"></i></a>\n");
      out.write("                        <ul class=\"ulPerfil\">\n");
      out.write("                            <li><a href=\"homeDepoisDeLogar.jsp\" id=\"liUm\" class=\"aMenu\"><i class=\"fas fa-home\"></i>Home</a></li>\n");
      out.write("                            <li><a class=\"aMenu\" onclick=\"document.getElementById('modal-wrapper').style.display='block'\" ><i class=\"fas fa-user-cog\"></i>Perfil</a></li>\n");
      out.write("                            <li><a href=\"chat.jsp\" class=\"aMenu\" ><i class=\"far fa-comment-dots\"></i>Chat</a></li>\n");
      out.write("                            <li><a href=\"#\" class=\"aMenu\" ><i class=\"fas fa-power-off\"></i>Sair</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("                    \n");
      out.write("                    <li class=\"liNav\"><a href=\"solicitarCarona.jsp\" class=\"aNav\"><i class=\"fas fa-search\"></i>Solicitar Carona</a></li>\n");
      out.write("                    <li class=\"liNav\"><a href=\"oferecerCarona.jsp\" class=\"aNav\"><i class=\"fas fa-plus-circle\"></i>Oferecer Carona</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </nav>\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("<!-- ----------- Perfil -------------- -->\n");
      out.write("    <div id=\"modal-wrapper\" class=\"modal\">\n");
      out.write("        <form class=\"modal-content animate\" action=\"/action_page.php\">\n");
      out.write("            <div class=\"imgcontainer\">\n");
      out.write("              <span onclick=\"document.getElementById('modal-wrapper').style.display='none'\" class=\"close\" title=\"Close PopUp\">&times;</span>\n");
      out.write("              <div  class=\"avatar\" id=\"\" style=\"background-image: url(img/1.png)\"></div>\n");
      out.write("              <div id=\"btnEditImg\" class=\"btnEditImg\">\n");
      out.write("                  <label id=\"fotoUser\" for=\"trocaFoto\"><i class=\"fas fa-edit\" style=\"color:coral;\"></i></label>\n");
      out.write("                  <input type=\"file\" id=\"trocaFoto\">\n");
      out.write("              </div>\n");
      out.write("             </div>\n");
      out.write("      \n");
      out.write("            <div class=\"container\">\n");
      out.write("              <div class=\"dadosUser\">\n");
      out.write("                  <h1 class=\"textosMain\">SoftPlayer</h1>\n");
      out.write("                  <p id=\"nomeUser\" class=\"textosSeg\">Yan Weschenfelder</p>\n");
      out.write("              </div>\n");
      out.write("                <div id=\"btnEditUser\" class=\"btns\">\n");
      out.write("                    <a onclick=\"lala()\"><i class=\"fas fa-edit\" style=\"color:coral;\"></i></a>\n");
      out.write("              </div>\n");
      out.write("      \n");
      out.write("              <div class=\"dadosProf\">\n");
      out.write("                  <h1 class=\"textosMain\">Profissão</h1>\n");
      out.write("                  <p id=\"nomeProf\" class=\"textosSeg\">Programador</p>\n");
      out.write("              </div>\n");
      out.write("              <div id=\"btnEditProf\" class=\"btns\">\n");
      out.write("                      <a onclick=\"lala()\"><i class=\"fas fa-edit\" style=\"color:coral;\"></i></a>\n");
      out.write("              </div>\n");
      out.write("      \n");
      out.write("              <div class=\"dadosTempo\">\n");
      out.write("                      <h1 class=\"textosMain\">Tempo na SoftPlan</h1>\n");
      out.write("                      <p id=\"nomeTempo\" class=\"textosSeg\">2 anos</p>\n");
      out.write("              </div>\n");
      out.write("              <div id=\"btnEditTemp\" class=\"btns\">\n");
      out.write("                      <a onclick=\"lala()\"><i class=\"fas fa-edit\" style=\"color:coral;\"></i></a>\n");
      out.write("              </div>\n");
      out.write("      \n");
      out.write("              <div class=\"dadosCont\">\n");
      out.write("                  <h1 class=\"textosMain\">Contato</h1>\n");
      out.write("                  <p id=\"nomeCont\" class=\"textosSeg\">(48)996894386</p>\n");
      out.write("              </div>\n");
      out.write("              <div id=\"btnEditCont\" class=\"btns\">\n");
      out.write("                 <a onclick=\"lala()\"><i class=\"fas fa-edit\" style=\"color:coral;\"></i></a>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("      \n");
      out.write("    </body>\n");
      out.write("     <script src=\"https://kit.fontawesome.com/7136158624.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("     <!-- -------- Oferecer Carona ------------ --> \n");
      out.write("    <div class=\"centro\">\n");
      out.write("        <div class=\"form\">\n");
      out.write("            <h1 class=\"textos\">De onde você vai sair ?</h1>\n");
      out.write("            <input type=\"search\" class=\"form-field\" id=\"pSair\" placeholder=\"Bairro / Empresa / Escritório\"/>\n");
      out.write("            <span id=\"erroPsair\"></span>\n");
      out.write("            <h1 class=\"textos\">Para onde deseja ir ?</h1>\n");
      out.write("            <input type=\"search\" class=\"form-field\" id=\"pVai\" placeholder=\"Bairro / Empresa / Escritório\"/>\n");
      out.write("            <span id=\"erroPvai\"></span>\n");
      out.write("            <h1 class=\"textos\">Horário de saída ?</h1>\n");
      out.write("            <input type=\"time\" class=\"form-field\" id=\"hora\"placeholder=\"Horário\"/>\n");
      out.write("            <span id=\"erroHora\"></span>\n");
      out.write("            <h1 class=\"textos\">Dia(s) de saída ?</h1>\n");
      out.write("            <input type=\"date\" class=\"form-field\" id=\"dia\" placeholder=\"Data\"/>\n");
      out.write("            <span id=\"erroDia\"></span>\n");
      out.write("            <h1 class=\"textos\">Quantos assentos disponíveis ?</h1>\n");
      out.write("            <input type=\"number\" id=\"assentos\" min=\"1\" max=\"6\" value=\"1\" class=\"form-field\" placeholder=\"Assento\"/>\n");
      out.write("            <span id=\"erroAssentos\"></span>\n");
      out.write("            <h1 class=\"textos\">Taxa(opcional) ?</h1>\n");
      out.write("            <input type=\"number\" id=\"taxa\" value=\"0\" class=\"form-field\" placeholder=\"Taxa\"/>\n");
      out.write("            <span id=\"erroTaxa\"></span>\n");
      out.write("            <input type=\"button\" class=\"form-button\" onclick=\"return conferirOC()\" value=\"ADICIONAR CARONA\"/>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("<script src=\"js/Verificacao.js\"></script>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
